/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tailor_project_final;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PRADEEPRAJ
 */
public class Customer_Registration extends javax.swing.JInternalFrame {

    /**
     * Creates new form Customer_Registration
     */
    public Customer_Registration() {
        initComponents();
    }
    public void Disables()//disables the textfields
    {
        CustId.setEnabled(false);
        CustName.setEnabled(true);
    
    }
    public void clear()//for clearing the text fields
    {
        CustId.setText("");
        CustName.setText("");
        //RCustFemale.isSelected(false);
        //RCustFemale
        CustAdd1.setText(""); 
        CustAdd2.setText(""); 
        CustMobile.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CustId = new javax.swing.JTextField();
        CustName = new javax.swing.JTextField();
        CustAdd1 = new javax.swing.JTextField();
        CustMobile = new javax.swing.JTextField();
        CustAdd2 = new javax.swing.JTextField();
        RCustMale = new javax.swing.JRadioButton();
        RCustFemale = new javax.swing.JRadioButton();
        jButton_old = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_modify = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jButton_new = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Customer Registration");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DATE");

        Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Date.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TIME");

        Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Time.setText("jLabel4");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Customer ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Customer Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Address 1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address 2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mob.Number");

        CustId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustIdActionPerformed(evt);
            }
        });

        CustName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CustAdd1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CustMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CustMobileKeyPressed(evt);
            }
        });

        CustAdd2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(RCustMale);
        RCustMale.setSelected(true);
        RCustMale.setText("Male");
        RCustMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCustMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(RCustFemale);
        RCustFemale.setText("Female");
        RCustFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCustFemaleActionPerformed(evt);
            }
        });

        jButton_old.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_old.setText("Old Cust Details");
        jButton_old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_oldActionPerformed(evt);
            }
        });

        jButton_ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_ok.setText("OK");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jButton_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_update.setText("Updatation for Cust detailis");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_modify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_modify.setText("Adding new Items to old Customer");
        jButton_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifyActionPerformed(evt);
            }
        });

        jButton_save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_save.setText("Save");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_new.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_new.setText("New Cust Reg");
        jButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(65, 65, 65)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(CustAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(CustAdd2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RCustMale)
                        .addGap(18, 18, 18)
                        .addComponent(RCustFemale))
                    .addComponent(CustName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(CustId, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_old, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(Time))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_old))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RCustMale)
                            .addComponent(RCustFemale))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton_new)
                        .addGap(33, 33, 33)
                        .addComponent(jButton_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CustAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CustAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CustMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_save)
                    .addComponent(jButton_ok))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustIdActionPerformed

    private void RCustMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCustMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RCustMaleActionPerformed

    private void RCustFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCustFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RCustFemaleActionPerformed

    private void jButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_newActionPerformed
        // For registering the new customer
        //  -------   CREATING NEW CUSTOMER ID-------------------
        clear();
        Disables();
        try{
        String custid;
                java.sql.Connection Connect;
                 Connect = Myjava.Myconnection.myconn();
                    PreparedStatement pt = Connect.prepareStatement("select * from Cust_Entry Where Cust_ID=(Select MAX(Cust_ID) from Cust_Entry)");
                    ResultSet rs = pt.executeQuery();
                    rs.next();
                    custid = rs.getString("Cust_ID"); 
                    custid=custid.substring(3).trim();
                    int no = Integer.parseInt(custid)+1;
                    
                    if(no<10)
                           custid="CUS000"+no;
                    else if(no<100)
                            custid="CUS00"+no;
                    else if(no<1000)
                            custid="CUS0"+no;
                    else
                            custid="CUS"+no;
                    CustId.setText(custid);
                    pt.close();
                    Connect.close();
            }catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
                jButton_new.setEnabled(false);
                jButton_modify.setEnabled(false);
                jButton_save.setEnabled(true);
                jButton_update.setEnabled(false);
                jButton_old.setEnabled(false);
                jButton_ok.setEnabled(false);
        
    }//GEN-LAST:event_jButton_newActionPerformed

    private void jButton_oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_oldActionPerformed
        //-----------Checking the old customers data
        try{
                String custid,custname,rbutton,custadd1,custadd2,custmob;
                Component c =(Component)evt.getSource();
                custid =JOptionPane.showInputDialog(c,"Customer ID");
                
                
                                
                java.sql.Connection Connect;
                Connect = Myjava.Myconnection.myconn();
                    PreparedStatement pt = Connect.prepareStatement("select * from Cust_Entry Where Cust_ID = ?");
                    pt.setString(1,custid.trim());
                    ResultSet rs = pt.executeQuery();
                    rs.next();
                    
                    custid = rs.getString("Cust_ID"); 
                    custname = rs.getString("Cust_Name");
                             
                    rbutton = rs.getString("Cust_Gen");
                                       
                    custadd1 = rs.getString("Cust_Add1");
                    custadd2 = rs.getString("Cust_Add2");
                    custmob = rs.getString("Cust_Mob").trim();
                    CustId.setText(custid);
                    CustName.setText(custname);
                    
                    
                    
                    
                    if(rbutton.equals("Male"))
                    {
                        RCustMale.setSelected(true);
                    }
                    else
                    {
                        //System.out.println(rbutton);
                        RCustFemale.setSelected(true);
                    }
                        
                    
                    CustAdd1.setText(custadd1);
                    CustAdd2.setText(custadd2);
                    CustMobile.setText(custmob);
                    
                     pt.close();
                    Connect.close();
                   jButton_new.setEnabled(false);
                   jButton_modify.setEnabled(false);
                   jButton_save.setEnabled(false);
                   jButton_update.setEnabled(false);
                   jButton_old.setEnabled(false);
                   jButton_ok.setEnabled(true);
                 
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this," Record Not Found");
            System.out.println(e.getMessage()); 
            this.dispose();
            this.setVisible(true);
        }
                
    }//GEN-LAST:event_jButton_oldActionPerformed

    private void jButton_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifyActionPerformed
        
        // ------------ TO ADDING THE EXTRA STITCHING MATERIAL FOR OLD CUSTOMER -----------------
        try{
                String custid,custname,rbutton,custadd1,custadd2,custmob;
                Component c =(Component)evt.getSource();
                custid =JOptionPane.showInputDialog(c,"Customer ID");
                java.sql.Connection Connect;
                Connect = Myjava.Myconnection.myconn();
                    PreparedStatement pt = Connect.prepareStatement("select * from Cust_Entry Where Cust_ID = ?");
                    pt.setString(1,custid.trim());
                    ResultSet rs = pt.executeQuery();
                    rs.next();
                    
                    custid = rs.getString("Cust_ID"); 
                    custname = rs.getString("Cust_Name");
                             
                    rbutton = rs.getString("Cust_Gen");
                                       
                    custadd1 = rs.getString("Cust_Add1");
                    custadd2 = rs.getString("Cust_Add2");
                    custmob = rs.getString("Cust_Mob").trim();
                    CustId.setText(custid);
                    CustName.setText(custname);
                    
                    
                    
                    
                    if(rbutton.equals("Male"))
                    {
                        RCustMale.setSelected(true);
                    }
                    else
                    {
                        //System.out.println(rbutton);
                        RCustFemale.setSelected(true);
                    }
                        
                    
                    CustAdd1.setText(custadd1);
                    CustAdd2.setText(custadd2);
                    CustMobile.setText(custmob);
                    
                     pt.close();
                    Connect.close();
                   
                 
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this," Record Not Found");
            System.out.println(e.getMessage()); 
        }
        
        jButton_new.setEnabled(false);
        jButton_modify.setEnabled(false);
        jButton_save.setEnabled(false);
        jButton_update.setEnabled(false);
         jButton_old.setEnabled(false);
         jButton_ok.setEnabled(false);
      // TO MOVE TO NEXT FRAME
       
        this.dispose();
        Data_Entry_New d = new Data_Entry_New();
        MainFrame.Mainframe.add(d);
        d.setVisible(true);
         
    }//GEN-LAST:event_jButton_modifyActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        //------------- UPDATING THE MODIFIED RECORD--------------------------------
        
        String custid,custname,rbutton,custadd1,custadd2,custmob;
               custid=CustId.getText().trim();
               custname=CustName.getText().trim();
               if (RCustMale.isSelected())
               {
                   rbutton="Male";
               }else
               {
                   rbutton="Female";
               }
               custadd1=CustAdd1.getText().trim();
               custadd2=CustAdd2.getText().trim();
               custmob=CustMobile.getText().trim();
               
               try
                    {
                   java.sql.Connection Connect;
                   Connect = Myjava.Myconnection.myconn();
                   PreparedStatement pt = Connect.prepareStatement("Update Cust_Entry set Cust_Name='"+custname+"',Cust_Gen='"+rbutton+"',Cust_Add1='"+custadd1+"',Cust_Mob='"+custmob+"',Cust_Add2 = ' "+custadd2+" ' where Cust_ID='"+custid+"' ");
                   
                  
                   int x = pt.executeUpdate();
                   
                   JOptionPane.showMessageDialog(this,custid);
                   
                   if(x > 0)
                    {
                            JOptionPane.showMessageDialog(this,"Record Updated");
                
                
                    }else
                    {
                             JOptionPane.showMessageDialog(this," Record Not Updated");
                    }
                    pt.close();
                    Connect.close(); 
                   
                    }
               catch(Exception e)
                    {
                         System.out.println(e.getMessage());  
                    }
               jButton_new.setEnabled(false);
        jButton_modify.setEnabled(false);
        jButton_save.setEnabled(false);
        jButton_update.setEnabled(false);
         jButton_old.setEnabled(false);
         jButton_ok.setEnabled(false);
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        // ----------INSERTING VALUES INTO DATABASE  --------------
        
        
        String custid,custname,rbutton,custadd1,custadd2,custmob;
               custid=CustId.getText().trim();
               custname=CustName.getText().trim();
               if (RCustMale.isSelected())
               {
                   rbutton="Male";
               }else
               {
                   rbutton="Female";
               }
               custadd1=CustAdd1.getText().trim();
               custadd2=CustAdd2.getText().trim();
               custmob=CustMobile.getText().trim();
               
               try
                    {
                   java.sql.Connection Connect;
                   Connect = Myjava.Myconnection.myconn();
                   PreparedStatement pt = Connect.prepareStatement("Insert into Cust_Entry (Cust_ID,Cust_Name,Cust_Gen,Cust_Mob,Cust_Add1,Cust_Add2)Values(?,?,?,?,?,?)");
                   pt.setString(1,custid);
                   pt.setString(2,custname);
                   pt.setString(3,rbutton);
                   pt.setString(4,custmob);
                   pt.setString(5,custadd1);
                   pt.setString(6,custadd2);
                   int x = pt.executeUpdate();
                   
                   
                   if(x > 0)
                    {
                            JOptionPane.showMessageDialog(this,"inserted");
                            
                
                    }else
                    {
                             JOptionPane.showMessageDialog(this," Not inserted");
                    }
                    pt.close();
                    Connect.close(); 
                   
                    }
               catch(Exception e)
                    {
                         System.out.println(e.getMessage());  
                    }
               // TO MOVE TO NEXT FRAME
        this.dispose();
        Data_Entry_New d = new Data_Entry_New();
        MainFrame.Mainframe.add(d);
        d.setVisible(true);
                       
                    
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        // TO MOVE TO NEXT FRAME
       
        this.dispose();
        Data_Entry_Old d = new Data_Entry_Old();
        MainFrame.Mainframe.add(d);
        d.setVisible(true);
        
    }//GEN-LAST:event_jButton_okActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // ------TO SET AN DATE AND TIME 
         Date date = new Date();
        SimpleDateFormat sdf;
        SimpleDateFormat sdt;
        sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Date.setText(sdf.format(date));
        sdt = new SimpleDateFormat(" hh:mm:ss");
        Time.setText(sdt.format(date));
    }//GEN-LAST:event_formInternalFrameOpened

    private void CustMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustMobileKeyPressed
        // -------------FOR NUMBER FORMAT----------------
        String ph = CustMobile.getText();
        int len = ph.length();
        char c =evt.getKeyChar();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(len<10){
                CustMobile.setEditable(true);
            }else{
                CustMobile.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                CustMobile.setEditable(true);
            }else{
                CustMobile.setEditable(false);
            }
        }
          
    }//GEN-LAST:event_CustMobileKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustAdd1;
    private javax.swing.JTextField CustAdd2;
    public static javax.swing.JTextField CustId;
    private javax.swing.JTextField CustMobile;
    public static javax.swing.JTextField CustName;
    private javax.swing.JLabel Date;
    public static javax.swing.JRadioButton RCustFemale;
    public static javax.swing.JRadioButton RCustMale;
    private javax.swing.JLabel Time;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_modify;
    private javax.swing.JButton jButton_new;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JButton jButton_old;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
