/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tailor_project_final;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PRADEEPRAJ
 */
public class Cutting_Processer extends javax.swing.JInternalFrame {
    DefaultTableModel dm;
    /**
     * Creates new form Cutting_Processer
     */
    public Cutting_Processer() {
        initComponents();
        CreateColumn();
        CreateRows();
    }
    private void CreateColumn(){//TO POPULATE COLUMN IN JTABLE
        dm=(DefaultTableModel) jTable1.getModel();
        dm.addColumn("CUSTOMER ID");
        dm.addColumn("ITEM");
        dm.addColumn("STATUS");
        dm.addColumn("Quantity");
       
    }
    private void CreateRows(){//TO POPULATE ROWS IN JTABLE
        try{
                         java.sql.Connection Connect;
                Connect = Myjava.Myconnection.myconn();
                    PreparedStatement pt = Connect.prepareStatement("select * from Status");
                 
                    ResultSet rs = pt.executeQuery();
                    while(rs.next()){
                    
                   String custid = rs.getString("Cust_ID"); 
                   String itm = rs.getString("Item");
                   String sta = rs.getString("status");
                  String qn  = rs.getString("Quantity");
                  String[] rowdata ={custid,itm,sta,qn};
                 dm.addRow(rowdata);
                 
                    }
                    pt.close();
                    Connect.close();
            }catch(Exception e){
                      JOptionPane.showMessageDialog(this,"ERROR OCCURS");
                      
              System.out.println(e.getMessage());

               }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Cust_id = new javax.swing.JTextField();
        Cust_name = new javax.swing.JTextField();
        Cust_mob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Orded_date = new javax.swing.JTextField();
        Delivery_date = new javax.swing.JTextField();
        Itm_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Measurement Of Items Need To Cut");
        setPreferredSize(new java.awt.Dimension(681, 541));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Date");

        Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Date.setText("Date");

        Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Time.setText("Time");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Customer ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Customer Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Customer Mob.No");

        Cust_id.setEditable(false);
        Cust_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Cust_name.setEditable(false);
        Cust_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cust_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_nameActionPerformed(evt);
            }
        });

        Cust_mob.setEditable(false);
        Cust_mob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ordered.Date");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Delivery.Date");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Item Name");

        Orded_date.setEditable(false);
        Orded_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Delivery_date.setEditable(false);
        Delivery_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Itm_name.setEditable(false);
        Itm_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jList1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Measurements");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Move for Stitiching");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cust_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Orded_date, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delivery_date, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cust_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Itm_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Date)
                            .addComponent(jLabel4)
                            .addComponent(Time))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cust_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(Cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(Cust_mob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(Orded_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delivery_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Itm_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel11)
                                .addGap(221, 221, 221)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        setBounds(0, 0, 1024, 625);
    }// </editor-fold>//GEN-END:initComponents

    private void Cust_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_nameActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // ------TO FILL DATE AND TIME
        Date date = new Date();
        SimpleDateFormat sdf;
        SimpleDateFormat sdt;
        sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Date.setText(sdf.format(date));
        sdt = new SimpleDateFormat(" hh:mm:ss");
        Time.setText(sdt.format(date));
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // -------TO MOVE THE VALUE TO ANOTHER TABLE--------
         String ctid=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
        String it = jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
        String mb = Cust_mob.getText().trim();
       // System.out.println(mb);
        String cnme,itm,orddt,deldt,gn,stat,qnu;
       // System.out.println(ctid);
        try{
         java.sql.Connection Connect;
                Connect = Myjava.Myconnection.myconn();
         PreparedStatement pt1 = Connect.prepareStatement("select * from Status where Cust_ID = ? and Item = ?");
                    pt1.setString(1, ctid.trim());
                    pt1.setString(2, it);

                    ResultSet rs1 = pt1.executeQuery();
                    rs1.next();
                    cnme = rs1.getString("Cust_Name");
                    gn = rs1.getString("Cust_Gen");
                    itm=rs1.getString("Item");
                    orddt = rs1.getString("Order_Date");
                    deldt= rs1.getString("Delivery_Date");
                    stat = rs1.getString("status");
                    qnu = rs1.getString("Quantity");
  PreparedStatement pt = Connect.prepareStatement("Insert into In_Process (Cust_ID,Cust_Name,Cust_Gen,Cust_Mob,Item,Order_Date,Delivery_Date,status,Quantity)Values(?,?,?,?,?,?,?,?,?)");

                  pt.setString(1,ctid);
                 pt.setString(2,cnme); 
                   pt.setString(3,gn);
                pt.setString(4,mb);
                   pt.setString(5,itm);
                   pt.setString(6,orddt);
                   pt.setString(7,deldt);
                   pt.setString(8,stat);
                   pt.setString(9, qnu);
                   int x = pt.executeUpdate();
                   if(x > 0)
                    {
                            JOptionPane.showMessageDialog(this,"MOVED TO STICHING PROCESS");
                            
                
                    }else
                    {
                             JOptionPane.showMessageDialog(this,"404 ERROR FOUND");
                    }
                    pt.close();
                    pt1.close();
                    Connect.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error");
            System.out.print(e.getMessage());
        }
        //------TO DELETE THE VALUES IN THE STATUS TABLE---------
        try{
            String nm = Cust_name.getText();
           String od = Orded_date.getText();
          String dd = Delivery_date.getText();
          String st = jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
         String q = jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();

            java.sql.Connection Connect;
             Connect = Myjava.Myconnection.myconn();
             PreparedStatement pt = Connect.prepareStatement("delete from Status where Cust_ID = ? and Cust_Name = ? and Item = ? and Order_Date = ? and Delivery_Date = ? and status = ? and Quantity = ? ");
             pt.setString(1,ctid);
             pt.setString(2,nm);
             pt.setString(3,it);
             pt.setString(4,od);
             pt.setString(5,dd);
             pt.setString(6,st);
             pt.setString(7,q);
             
            // ResultSet rs1 = pt.executeQuery();
            pt.execute();
             pt.close();
             //System.out.println(cnme);
             Connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
         dm=(DefaultTableModel) jTable1.getModel();
         dm.setRowCount(0);
         CreateRows();
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // -------TO FILL THE FORM-------
        String s,custid,custname,custmob,itm,orddt,deldt;
        s = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
        try{
            java.sql.Connection Connect;
                Connect = Myjava.Myconnection.myconn();
                    PreparedStatement pt = Connect.prepareStatement("select * from Cust_Entry Where Cust_ID = ?");
                    pt.setString(1,s.trim());
                    ResultSet rs = pt.executeQuery();
                    rs.next();
                    
                    custid = rs.getString("Cust_ID"); 
                    custname = rs.getString("Cust_Name");
                    custmob = rs.getString("Cust_Mob").trim();
                    Cust_id.setText(custid);
                    Cust_name.setText(custname);
                    Cust_mob.setText(custmob);
                    PreparedStatement pt1 = Connect.prepareStatement("select * from Status where Cust_ID = ?");
                    pt1.setString(1, s.trim());
                    ResultSet rs1 = pt1.executeQuery();
                    rs1.next();
                    itm=rs1.getString("Item");
                    orddt = rs1.getString("Order_Date");
                    deldt= rs1.getString("Delivery_Date");
                    Orded_date.setText(orddt.trim());
                    Delivery_date.setText(deldt.trim());
                    Itm_name.setText(itm);
                    
                    pt1.close();
                    pt.close();
                    Connect.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this," Record Not Found");
            System.out.println(e.getMessage()); 
        }
        DefaultListModel m=new DefaultListModel();

            String s2=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
             String s1=jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();

            try{
                         java.sql.Connection Connect;
                Connect = Myjava.Myconnection.myconn();
             PreparedStatement pt1 = Connect.prepareStatement("select * from Cust_Data_Entry Where item_name = ? and Cust_ID = ?");
                          pt1.setString(1,s1);
                          pt1.setString(2,s2);
                          ResultSet rs1 = pt1.executeQuery();

                        while(rs1.next()){
                              String i=rs1.getString("Measurement_List");
                             String itname=rs1.getString("Measurement");
                              m.addElement(i +" "+ ":"+" "+itname);
                         }
                        jList1.setModel(m);
                        
                     // String f =jList1.getSelectedValue().toString();
                     
                          // PreparedStatement pt =Connect.prepareStatement("select *")

              //System.out.println(f);
                         pt1.close();
                    Connect.close();
             
            }catch(Exception e){
                      JOptionPane.showMessageDialog(this,"ERROR");
                      
              System.out.println(e.getMessage());

               }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cust_id;
    private javax.swing.JTextField Cust_mob;
    private javax.swing.JTextField Cust_name;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField Delivery_date;
    private javax.swing.JTextField Itm_name;
    private javax.swing.JTextField Orded_date;
    private javax.swing.JLabel Time;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
