/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tailor_project_final;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PRADEEPRAJ
 */
public class Items extends javax.swing.JInternalFrame {

    /**
     * Creates new form Items
     */
    public Items() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ItmID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        itmname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        rmale = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Itmnew = new javax.swing.JButton();
        itmsave = new javax.swing.JButton();
        itmmodi = new javax.swing.JButton();
        itmupdate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(463, 468));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Date");

        Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Date.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Time");

        Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Time.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Item ID");

        ItmID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Item Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Price");

        itmname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(rmale);
        rmale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rmale.setText("Male");
        rmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Female");

        Itmnew.setText("New");
        Itmnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmnewActionPerformed(evt);
            }
        });

        itmsave.setText("Save");
        itmsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmsaveActionPerformed(evt);
            }
        });

        itmmodi.setText("Modify");
        itmmodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmmodiActionPerformed(evt);
            }
        });

        itmupdate.setText("Update");
        itmupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(Date)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(Time)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(53, 53, 53)
                                .addComponent(ItmID))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(55, 55, 55))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price)
                                    .addComponent(itmname)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rmale)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Itmnew)
                            .addComponent(itmsave)
                            .addComponent(itmmodi)
                            .addComponent(itmupdate))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Date)
                            .addComponent(jLabel3)
                            .addComponent(Time))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(ItmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Itmnew))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(itmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itmsave))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rmale)
                        .addComponent(jRadioButton2)
                        .addComponent(itmmodi)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(itmupdate))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmaleActionPerformed

    private void ItmnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmnewActionPerformed
        // TODO add your handling code here:
        //-----ADDING NEW ITEMS
        try{
        String itemid;
                java.sql.Connection Connect;
                 Connect = Myjava.Myconnection.myconn();
                    PreparedStatement pt = Connect.prepareStatement("select * from item_entry Where Item_ID=(Select MAX(Item_ID) from item_entry)");
                    ResultSet rs = pt.executeQuery();
                    rs.next();
                    itemid = rs.getString("Item_ID"); 
                    itemid=itemid.substring(3).trim();
                    int no = Integer.parseInt(itemid)+1;
                    
                    if(no<10)
                           itemid="ITM000"+no;
                    else if(no<100)
                            itemid="ITM00"+no;
                    else if(no<1000)
                            itemid="ITM0"+no;
                    else
                            itemid="ITM"+no;
                    ItmID.setText(itemid);
                    pt.close();
                    Connect.close();
            }catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
                Itmnew.setEnabled(false);
                itmmodi.setEnabled(false);
                itmsave.setEnabled(true);
                itmupdate.setEnabled(false);

                                         

                                          

   
                                         

                                         
        
    }//GEN-LAST:event_ItmnewActionPerformed

    private void itmsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmsaveActionPerformed
        // TODO add your handling code here:
                 String itemid,itemname,rbutton,pri;
               itemid=ItmID.getText().trim();
               itemname=itmname.getText().trim();
               if (rmale.isSelected())
               {
                   rbutton="Male";
               }else
               {
                   rbutton="Female";
               }
               pri=price.getText().trim();
               
               try
                    {
                   java.sql.Connection Connect;
                   Connect = Myjava.Myconnection.myconn();
                   PreparedStatement pt = Connect.prepareStatement("Insert into item_entry (Item_ID,Item_Name,Gender,price)Values(?,?,?,?)");
                   pt.setString(1,itemid);
                   pt.setString(2,itemname);
                   pt.setString(3,rbutton);
                   pt.setString(4,pri);
                   int x = pt.executeUpdate();
                   
                   
                   if(x > 0)
                    {
                            JOptionPane.showMessageDialog(this,"inserted");
                           // clear();
                
                    }else
                    {
                             JOptionPane.showMessageDialog(this," Not inserted");
                    }
                    pt.close();
                    Connect.close(); 
                   
                    }
               catch(Exception e)
                    {
                         System.out.println(e.getMessage());  
                    }
                Itmnew.setEnabled(false);
                itmmodi.setEnabled(false);
                itmsave.setEnabled(true);
                itmupdate.setEnabled(false);
    }//GEN-LAST:event_itmsaveActionPerformed

    private void itmmodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmmodiActionPerformed
        // TODO add your handling code here:
                try{
                String itemid,itemname,rbutton,pri;
                itemname =JOptionPane.showInputDialog("ITEM ID");
                
                
                                
                java.sql.Connection Connect;
                Connect = Myjava.Myconnection.myconn();
                    PreparedStatement pt = Connect.prepareStatement("select * from item_entry Where Item_ID = ?");
                    pt.setString(1,itemname.trim());
                    ResultSet rs = pt.executeQuery();
                    rs.next();
                    
                    itemid = rs.getString("Item_ID"); 
                    itemname = rs.getString("Item_Name");
                             
                    rbutton = rs.getString("Gender");
                                       
                    pri = rs.getString("Price");
                    ItmID.setText(itemid);
                    itmname.setText(itemname);
                    if(rbutton.equals("Male"))
                    {
                        rmale.setSelected(true);
                    }
                    else
                    {
                        System.out.println(rbutton);
                    }
                        
                    
                    price.setText(pri);
                    
                     pt.close();
                    Connect.close();
                   
                 
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this," Record Not Found");
            System.out.println(e.getMessage()); 
        }
                Itmnew.setEnabled(false);
                itmmodi.setEnabled(false);
                itmsave.setEnabled(false);
                itmupdate.setEnabled(true);
    }//GEN-LAST:event_itmmodiActionPerformed

    private void itmupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmupdateActionPerformed
        // TODO add your handling code here:
             String itmid,itemname,rbutton,pri;
               itmid=ItmID.getText().trim();
               itemname=itmname.getText().trim();
               if (rmale.isSelected())
               {
                   rbutton="Male";
               }else
               {
                   rbutton="Female";
               }
               pri=price.getText().trim();
               
               
               try
                    {
                   java.sql.Connection Connect;
                   Connect = Myjava.Myconnection.myconn();
                   PreparedStatement pt = Connect.prepareStatement("Update item_entry set Item_Name='"+itemname+"',Gender='"+rbutton+"',Price='"+pri +"' where Item_ID='"+itmid+"' ");
                   
                   int x = pt.executeUpdate();
                   
                   if(x > 0)
                    {
                            JOptionPane.showMessageDialog(this,"Record Updated");
                
                
                    }else
                    {
                             JOptionPane.showMessageDialog(this," Record Not Updated");
                    }
                    pt.close();
                    Connect.close(); 
                   
                    }
               catch(Exception e)
                    {
                         System.out.println(e.getMessage());  
                    }
    }//GEN-LAST:event_itmupdateActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Date date = new Date();
        SimpleDateFormat sdf;
        SimpleDateFormat sdt;
        sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Date.setText(sdf.format(date));
        sdt = new SimpleDateFormat(" hh:mm:ss");
        Time.setText(sdt.format(date));
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JTextField ItmID;
    private javax.swing.JButton Itmnew;
    private javax.swing.JLabel Time;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton itmmodi;
    private javax.swing.JTextField itmname;
    private javax.swing.JButton itmsave;
    private javax.swing.JButton itmupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField price;
    private javax.swing.JRadioButton rmale;
    // End of variables declaration//GEN-END:variables
}
